import type { Metadata } from 'next';

import SidebarNav from '@/components/SidebarNav/SidebarNav';
import UserInput from '@/components/UserInput/UserInput';
import AppProvider from '@/pages/AppContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="flex min-h-screen h-screen overflow-hidden">
      <AppProvider>
        <SidebarNav />
        <div className="flex-grow p-4 bg-[#585C72] flex flex-col">
          <div className="flex-grow overflow-auto">
            <UserInput />
          </div>
        </div>
      </AppProvider>
    </main>
  );
}
