import type { Metadata } from 'next';

import SidebarNav from '@/components/SidebarNav/SidebarNav';
import UserInput from '@/components/UserInput/UserInput';
import AppProvider from '@/pages/AppContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="flex min-h-screen h-screen overflow-hidden">
      <AppProvider>
        <SidebarNav />
        <UserInput />
      </AppProvider>
    </main>
  );
}
